#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh
source $(dirname $0)/utils.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/pipeline-discovery-resource-request

cat > $payload <&0

destination=$TMPDIR/git-semver-tag-resource

prepare_repository "$destination" "$payload"

# return latest tag on this branch
branch=$(jq -r '.source.branch // ""' < "$payload")
tag_prefix=$(jq -r '.source.tag_prefix // ""' < "$payload")
tags=$(git tag --merged "$branch" -l --sort=version:refname "${tag_prefix}*" 2>/dev/null)

if [ -z "$tags" ]; then
  initial_version=$(jq -r '.source.initial_version // "0.0.0"' < "$payload")
  jq -n "[{ number: \"$initial_version\" }]" >&3
else
  result="[]"
  while read tag; do
    tag_version=$(grep -Po "^${tag_prefix}\K.*$" <<<"${tag}")
    result+=" | . + [{ number: \"${tag_version}\" }]"
  done <<< "$tags"

  jq -n "$result" >&3
fi
