#!/bin/bash

set -e

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

git_semver_tag_resource_dir=$(cd $(dirname $0)/.. && pwd)

if not_installed docker; then
  echo "# docker is not installed! run the following commands:"
  echo "    brew install docker"
  echo "    brew cask install docker-machine"
  echo "    docker-machine create dev --driver virtualbox"
  echo '    eval $(docker-machine env dev)'
  echo "    docker login"
  exit 1
fi

name=laurentverbruggen/concourse-git-semver-tag-resource
cd $git_semver_tag_resource_dir
docker build --rm . -t $name
docker push $name
